#!/bin/bash -ex

# Has already been done. Unsure if we should rerun it here.
time python3 /app/manage.py collectstatic --noinput -v0

# Must be done when settings are available because it communicates with
# the cache.
time python3 /app/manage.py compress

# Start as www-data
exec /usr/bin/uwsgi /app/uwsgi.ini
